### ISSUE TITLE
C compiler does not work in sandbox on macOS High Sierra

### ISSUE THREAD

**Issue by jlmuir** [jmmv/sandboxctl#7]
On macOS High Sierra (10.13.1), I'm using [pkg_comp](https://github.com/jmmv/pkg_comp) which uses `sandboxctl`, and I drop into a sandbox shell:

```
$ sudo pkg_comp sandbox-create
$ sudo pkg_comp sandbox-shell
```

*Inside the sandbox*, I check that the path to the Xcode developer directory is correct, and try a simple C compiler command which fails:

```
# xcode-select -p
/Applications/Xcode.app/Contents/Developer
# cc -isystem /usr/include --version
cc: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
cc: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
```

Of course, there are also the Command Line Tools, but I believe they are not always sufficient: some software will not build with just the Command Line Tools; they require the full Xcode.app in order to build.  Nonetheless, in trying to characterize the failure, I set the Xcode developer directory *in the sandbox* to the Command Line Tools, and the above test succeeds:

```
# xcode-select --switch /Library/Developer/CommandLineTools
# xcode-select -p
/Library/Developer/CommandLineTools
# cc -isystem /usr/include --version
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by jlmuir** [comment]
I found `/macOS_SDK` on my system and guessed it's related to Xcode 9, so I tried bind-mounting it in the sandbox, but that seemed to have no effect. :-(

**Comment by jmmv** [comment]
Sorry for the delay. Catching up with old mail now...

The problem is not in the location of Xcode. From within the sandbox:

```
sh-3.2# cc
cc: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
cc: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
sh-3.2# xcodebuild
Killed: 9
```

Yikes. I'm afraid of debugging that: the [last similar issue I faced](http://julio.meroh.net/2017/10/fighting-execs-sandboxfs-macos.html) took a couple of days of poking, and I've confirmed that this issue is different :-/ But at least this should point in a different direction than the one you were investigating.

**Comment by jmmv** [comment]
But similar to the linked problem, `xcodebuild` seems to be killed very, very early. I tried copying the binary to `/tmp` and running it, and it then crashes with the inability to find shared libraries. Passing `DYLD_PRINT_RPATHS` shows progress, whereas it does not when running `xcodebuild` from its original location.

**Comment by jmmv** [comment]
This is as simple to reproduce as:

```
mkdir /tmp/mnt
bindfs / /tmp/mnt
chroot /tmp/mnt
xcodebuild # From within the chroot
```

**Comment by jmmv** [comment]
One thought would be to try to disable SIP (reboot the machine in recovery mode by holding Command+R at boot, enter a terminal, and type `csrutil disable`), reboot, and try again.

**Comment by jmmv** [comment]
Following the same reproduction case as above on macOS Mojave with Xcode 10.0 yields:

```
sh-3.2# xcodebuild
xcodebuild: error: couldn't create cache file '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/xcrun_db-JB2GNa3q' (errno=Permission denied)
Killed: 9
```

A more useful error message. May not be related to the original problem though, but it probably is.

**Comment by jmmv** [comment]
At least in the sandboxctl case, that `/var/folders/zz/...` directory has to be created upfront to let xcodebuild find it. But that doesn't fix the problem.

Interestingly, Mojave prints extra logs to dmesg about this event:

```
macOSTaskPolicy: (com.apple.dtrace) may not get the taskport of (xcodebuild) (pid: 4866): (xcodebuild) is hardened, (xcodebuild) doesn't have get-task-allow, (com.apple.dtrace) is a declared debuggersb_user_approval: kTCCServiceSystemPolicyAllFiles for fseventsd [55]sb_user_approval: pid 55 responsible for 55sb_user_approval: kTCCServiceSystemPolicyAllFiles satisifed from cache for pid 55: not approvedsb_user_approval: kTCCServiceSystemPolicyAllFiles for fseventsd [55]sb_user_approval: pid 55 responsible for 55sb_user_approval: kTCCServiceSystemPolicyAllFiles satisifed from cache for pid 55: not approvedAMFI: hook..execve() killing pid 4875: not allowed in chroot
```

I'm starting to think that the whole sandboxctl approach is doomed with SIP.

**Comment by jmmv** [comment]
Got `pkg_comp` to work again on macOS Mojave but had to disable SIP. I think I will stop fighting SIP and just tell users to disable it... Not great, but I don't see a better way.

Will see if I can submit the two small fixes needed to get things back to a functional state.
