### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by spl** [jmmv/sandboxctl#9]
Is it possible to get a new release of `sandboxctl`? In particular, I'm interested in the fix to #5 which I believe affects most macOS installations these days. I've been running into that problem, and I haven't found anybody else who has dealt with it.

**Comment by jmmv** [comment]
Yes. I was planning to cut one last week but ran out of time due to some home issues... Hopefully I can cut one sometime next week.

**Comment by jmmv** [comment]
Much later than originally promised... but done now. 1.1 is out. Sorry for the delay.
